title: 'Government of Singapore'
description: Description
url: 'https://www.engineerwhatsnext.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    meet-the-engineers:
        output: true
        permalink: '/:collection/:path/:title'
    engineering-marvels:
        output: true
        permalink: '/:collection/:path/:title'
    types-of-engineering:
        output: true
        permalink: '/:collection/:path/:title'
    engineering-careers:
        output: true
        permalink: '/:collection/:path/:title'
resources_name: resource-room
favicon: /images/favicon-ewnIcon.ico
google-analytics: UA-73732262-1
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
